# Generated by Django 5.1.7 on 2026-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username_last_changed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
