# Generated by Django 5.1.7 on 2026-03-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_username_last_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apple_user_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
