# Generated by Django 5.1.7 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_apple_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apple_music_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="apple_music_user_token",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
