# Generated by Django 5.1.7 on 2026-03-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_apple_music_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_petition_signed",
            field=models.BooleanField(default=False),
        ),
    ]
