# Generated by Django 5.1.7 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_spotify_petition_signed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apple_music_recent_track_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
