# Generated by Django 5.1.7 on 2026-02-16 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="music.album",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "album_ratings",
            },
        ),
        migrations.CreateModel(
            name="AlbumReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="music.album",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.albumrating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "album_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SongRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="music.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "song_ratings",
            },
        ),
        migrations.CreateModel(
            name="SongReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.songrating",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="music.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "song_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="albumrating",
            index=models.Index(
                fields=["user", "-created_at"], name="album_ratin_user_id_1e007f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="albumrating",
            index=models.Index(
                fields=["album", "-rating"], name="album_ratin_album_i_31d54c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="albumrating",
            unique_together={("user", "album")},
        ),
        migrations.AddIndex(
            model_name="albumreview",
            index=models.Index(
                fields=["user", "-created_at"], name="album_revie_user_id_0c470d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="albumreview",
            index=models.Index(
                fields=["album", "-created_at"], name="album_revie_album_i_970030_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="albumreview",
            unique_together={("user", "album")},
        ),
        migrations.AddIndex(
            model_name="songrating",
            index=models.Index(
                fields=["user", "-created_at"], name="song_rating_user_id_aae568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="songrating",
            index=models.Index(
                fields=["song", "-rating"], name="song_rating_song_id_b8fba8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songrating",
            unique_together={("user", "song")},
        ),
        migrations.AddIndex(
            model_name="songreview",
            index=models.Index(
                fields=["user", "-created_at"], name="song_review_user_id_1f159c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="songreview",
            index=models.Index(
                fields=["song", "-created_at"], name="song_review_song_id_3aa810_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songreview",
            unique_together={("user", "song")},
        ),
    ]
