# Generated by Django 5.1.7 on 2026-02-24 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albumrating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="songrating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AlbumReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reviews.albumreviewcomment",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.albumreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "album_review_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlbumReviewCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="reviews.albumreviewcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_review_comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "album_review_comment_likes",
            },
        ),
        migrations.CreateModel(
            name="SongReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reviews.songreviewcomment",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.songreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "song_review_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SongReviewCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="reviews.songreviewcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_review_comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "song_review_comment_likes",
            },
        ),
        migrations.AddIndex(
            model_name="albumreviewcomment",
            index=models.Index(
                fields=["review", "created_at"], name="album_revie_review__a170de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="albumreviewcomment",
            index=models.Index(
                fields=["parent"], name="album_revie_parent__1aeb3b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="albumreviewcommentlike",
            unique_together={("user", "comment")},
        ),
        migrations.AddIndex(
            model_name="songreviewcomment",
            index=models.Index(
                fields=["review", "created_at"], name="song_review_review__a2d0db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="songreviewcomment",
            index=models.Index(
                fields=["parent"], name="song_review_parent__8dae6a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songreviewcommentlike",
            unique_together={("user", "comment")},
        ),
    ]
