# Generated by Django 5.1.7 on 2026-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_albumreviewlike_songreviewlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumreview",
            name="content",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="albumreviewcomment",
            name="content",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="songreview",
            name="content",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="songreviewcomment",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
