# Generated by Django 5.1.7 on 2026-02-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("genres", models.JSONField(default=list)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "artists",
                "indexes": [
                    models.Index(
                        fields=["spotify_id"], name="artists_spotify_ce8006_idx"
                    ),
                    models.Index(fields=["name"], name="artists_name_b2ca99_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=500)),
                ("album_type", models.CharField(max_length=50)),
                ("release_date", models.CharField(max_length=50)),
                ("total_tracks", models.IntegerField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("genres", models.JSONField(default=list)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artists",
                    models.ManyToManyField(related_name="albums", to="music.artist"),
                ),
            ],
            options={
                "db_table": "albums",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=500)),
                ("track_number", models.IntegerField()),
                ("disc_number", models.IntegerField(default=1)),
                ("duration_ms", models.IntegerField()),
                ("explicit", models.BooleanField(default=False)),
                ("preview_url", models.URLField(blank=True, null=True)),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
                (
                    "artists",
                    models.ManyToManyField(related_name="songs", to="music.artist"),
                ),
            ],
            options={
                "db_table": "songs",
            },
        ),
        migrations.CreateModel(
            name="ListeningHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played_at", models.DateTimeField(db_index=True)),
                ("context_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="music.album",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "db_table": "listening_history",
                "ordering": ["-played_at"],
            },
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["spotify_id"], name="albums_spotify_f32988_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["name"], name="albums_name_fbf363_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-avg_rating"], name="albums_avg_rat_bdcf69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["spotify_id"], name="songs_spotify_b1958e_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["name"], name="songs_name_7003cd_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["-avg_rating"], name="songs_avg_rat_4ffcb3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="song",
            unique_together={("album", "track_number", "disc_number")},
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["user", "-played_at"], name="listening_h_user_id_481e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["song", "-played_at"], name="listening_h_song_id_644e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["-played_at"], name="listening_h_played__db3ae7_idx"
            ),
        ),
    ]
