# Generated by Django 5.1.7 on 2026-02-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="label",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="popularity",
        ),
    ]
