# Generated by Django 5.1.7 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_deprecated_spotify_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="song",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="album",
            name="apple_music_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="apple_music_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="apple_music_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="isrc",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="album",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="total_tracks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="artist",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="song",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="track_number",
            field=models.IntegerField(default=0),
        ),
    ]
