# Generated by Django 5.1.7 on 2026-04-04 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_add_apple_music_ids_and_isrc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listeninghistory",
            name="source_item_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="source_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["user", "source_provider", "source_item_id"],
                name="listening_h_user_id_49b7c4_idx",
            ),
        ),
    ]
